### PR TITLE
add windowHints hook

### PR DESCRIPTION
**Pull request by falood**
I wanna move cursor to window's center, but mjolnir don't support `event` now [mjolnir #72](https://github.com/sdegutis/mjolnir/issues/72).

So I add hook for `windowHints`. Is this the correct way to do it?

### CODE REVIEW

**Comment by trishume** [comment]
Derp was just fixing up my notification settings on Github and noticed that I've totally missed this.

Sorry! I'll take a look now.

**Comment by trishume** [comment]
Does lua support passing less than the requested number of parameters? Otherwise I don't want to break compatibility with the current interface.

If I'm wrong about this breaking existing user configs or you change this PR ping me and I will reopen and look at it again.

**Comment by falood** [comment]
I'm sorry but I have switched to [hammerspoon](http://www.hammerspoon.org/), which is another mjolnir fork.
Thank you for your awesome work!

**Comment by trishume** [comment]
I switched to Hammerspoon as well many months ago, which is why I totally ignored this project for so long.

**Pull request closed without merging**
